name: simple_doh_client
description: A simple DNS over Https Client.
version: 0.0.1
repository: https://github.com/navetacandra/dart_doh_client

environment:
  sdk: ^3.6.0

dependencies:
  http: ^1.2.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
